### ISSUE TITLE
Instructions for the Insights Report

### ISSUE THREAD

**Issue by nosro** [mirobotur/Flex-Focus-Time-with-Chat-Metrics#1]
The report in the main README documentation looks good. Is there a way you could share the steps in Insights to generate a report like that?

**Comment by mirobotur** [comment]
It's just a bogus dashboard with some example visualisations. You really should first design what exactly you would like to see in the dashboards and then create it with a little help of our support or here are really straighforward free trainings of Flex Insights:
https://www.twiliotraining.com/store/864202-flex-insights-overview
https://www.twiliotraining.com/store/901979-flex-insights-advanced-custom-reporting
https://www.twiliotraining.com/store/964117-flex-insights-advanced-custom-metrics
